# Generated by Django 5.1.1 on 2024-11-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DBSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "storage_method",
                    models.CharField(
                        choices=[("in_memory", "In Memory"), ("database", "Database")],
                        default="in_memory",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("row_id", models.AutoField(primary_key=True, serialize=False)),
                ("model_year", models.IntegerField()),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("vehicle_class", models.CharField(max_length=100)),
                ("engine_size", models.DecimalField(decimal_places=1, max_digits=4)),
                ("cylinders", models.IntegerField()),
                ("transmission", models.CharField(max_length=50)),
                ("fuel_type", models.CharField(max_length=50)),
                (
                    "city_fuel_efficiency",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "highway_fuel_efficiency",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "combined_fuel_efficiency",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("combined_mpg", models.IntegerField()),
                ("co2_emissions", models.IntegerField()),
                ("co2_rating", models.IntegerField()),
                ("smog_rating", models.IntegerField()),
            ],
        ),
    ]
